-- Supabase Schema for Efectivo Module

CREATE TABLE IF NOT EXISTS public.efectivo_cycles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.efectivo_initial_balances (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cycle_id BIGINT REFERENCES public.efectivo_cycles(id) ON DELETE CASCADE,
  driver_name TEXT NOT NULL,
  balance NUMERIC DEFAULT 0.0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.efectivo_uber_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cycle_id BIGINT REFERENCES public.efectivo_cycles(id) ON DELETE CASCADE,
  driver_name TEXT NOT NULL,
  period TEXT,
  month TEXT,
  cash_collected NUMERIC DEFAULT 0.0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(driver_name, period, cycle_id)
);

CREATE TABLE IF NOT EXISTS public.efectivo_entrega_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cycle_id BIGINT REFERENCES public.efectivo_cycles(id) ON DELETE CASCADE,
  driver_name TEXT NOT NULL,
  timestamp TEXT,
  month TEXT,
  amount NUMERIC DEFAULT 0.0,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(driver_name, timestamp, cycle_id)
);

CREATE TABLE IF NOT EXISTS public.efectivo_vgd_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cycle_id BIGINT REFERENCES public.efectivo_cycles(id) ON DELETE CASCADE,
  vgd_id BIGINT,
  driver_name TEXT NOT NULL,
  month TEXT,
  cash_collected NUMERIC DEFAULT 0.0,
  fecha_hora TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.efectivo_aliases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bad_name TEXT UNIQUE NOT NULL,
  good_name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.efectivo_upload_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cycle_id BIGINT REFERENCES public.efectivo_cycles(id) ON DELETE CASCADE,
  file_type TEXT,
  file_name TEXT,
  upload_time TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.efectivo_expense_records (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cycle_id BIGINT REFERENCES public.efectivo_cycles(id) ON DELETE CASCADE,
  driver_name TEXT NOT NULL,
  description TEXT,
  amount NUMERIC DEFAULT 0.0,
  timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- Seed an initial active cycle if none exist
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.efectivo_cycles WHERE is_active = true) THEN
    INSERT INTO public.efectivo_cycles (name, is_active) VALUES ('Ciclo 1', true);
  END IF;
END $$;
