ALTER TABLE public.drivers 
ADD COLUMN IF NOT EXISTS rotation_offset INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS rotation TEXT DEFAULT 'MAÑANA_SIEMPRE',
ADD COLUMN IF NOT EXISTS rest_day TEXT DEFAULT '1',
ADD COLUMN IF NOT EXISTS pattern TEXT DEFAULT 'Siempre 1',
ADD COLUMN IF NOT EXISTS rotation_freq INTEGER DEFAULT 2;
